### ISSUE TITLE
cgalv2m BUG

### ISSUE THREAD

**Issue by artturuohola** [fangq/iso2mesh#30]
![image](https://user-images.githubusercontent.com/25384082/57865103-a6caf800-7805-11e9-8461-57071f392a13.png)

I'm trying mesh a head volume specified by a volumetric uint8 image of 6 grayscale values (42.5000   85.0000  127.5000  170.0000  212.5000  255.0000)

Dimensions are 394x466 x620

I'm getting the following error:

Error using cgalv2m (line 87)
output file was not found, failure was encountered when running command: \n"C:\Users\Arttu\Documents\MATLAB\iso2mesh\bin\cgalmesh.exe"
"C:\Users\Arttu\AppData\Local\Temp\iso2mesh-Arttu\pre_cgalmesh.inr" "C:\Users\Arttu\AppData\Local\Temp\iso2mesh-Arttu\post_cgalmesh.mesh"
30.000000 2.000000 0.500000 3.000000 100.000000 1648335518

I have attached the zip of the pre_cgalmesh.inr

[pre_cgalmesh.zip](https://github.com/fangq/iso2mesh/files/3187727/pre_cgalmesh.zip)

**Comment by artturuohola** [comment]
I'm using v2m(head_volume,0.5,2,100,'cgalmesh')

**Comment by artturuohola** [comment]
I attached the grayscale volumetric brain image (new york head) to this message

[NY_Head.zip](https://github.com/fangq/iso2mesh/files/3188355/NY_Head.zip)

**Comment by fangq** [comment]
the issue was caused by the 32bit cgalmesh windows binary we shipped with iso2mesh. it can not handle memory more than 2GB. If I run the command on my 64bit Linux using a 64bit binary, I was able to generate the mesh (took about 2 min).

the solution is to checkout the win64 branch of the software from the below link:
https://github.com/fangq/iso2mesh/tree/win64

if you replace your iso2mesh/bin/cgalmesh.exe with the version from the above link, you should be able to get around this. Let me know if that is the case. Feel free to reopen the issue if this does not work.
