### ISSUE TITLE
cgalpoly for MacOS ARM 

### ISSUE THREAD

**Issue by cberggren** [fangq/iso2mesh#81]
Appreciate all the work developing this package! Very handy. 

I got an error saying that cgalpoly.mexmaca64 is missing. I checked https://github.com/fangq/iso2mesh/tree/master/bin/ and it looks like cgalpoly hasn't been compiled for ARM Macs? Would it be possible to get this recompiled? Thank you!

**Comment by fangq** [comment]
hi @cberggren, s2m/surf2mesh by default only uses tetgen for the tetrahedral mesh generation. In the past, I haven't actually found use of `cgalpoly`, so I thought the missing binary would not cause any shortage of key use cases. I am wondering if this request is caused by a specific need of this utility or just an observation for completeness?

**Comment by cberggren** [comment]
This was mostly just an observation for completeness, I have access to a Windows machine where I can run the `cgalpoly` option if needed.
